### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by jeroenst** [Webunity/node-red-contrib-dutch-weather#1]
When I deploy this node I get the following error:

Flows stopped due to missing node types.
dutch-weather-conf
meteoplaza

Although I did configure a location in the dutch-weather-conf

**Comment by gvdhoven** [comment]
Hi Jeroen, few questions:
1) which version did you deploy
2) did you install it via the pallete?
3) can you copy and paste the logfiles, maybe there is a javascript error logged.

**Comment by gvdhoven** [comment]
No reaction, closing issue.

**Comment by jeroenst** [comment]
Sorry for my late response. 
I installed via the palette. I don't know which version it was. I removed it already. 
Now I fetch data from xml.buienradar.nl
