### ISSUE TITLE
add inputs

### ISSUE THREAD

**Issue by janjansen1** [Webunity/node-red-contrib-dutch-weather#2]
Thanks for making "node-red-contrib-dutch-weather".  At the moment I only use the options azimuth and cloud coverage. I'ts a loss that the nodes have no input. Therefore it is not possible to select the desired call frequency yourself. Adding inputs makes your contribution much more flexible.

**Comment by gvdhoven** [comment]
Good idea, since this is my first node, how would you want to use it? like msg.interval as input if specified else fallback to default values?

**Comment by janjansen1** [comment]
Beste Gilles,

Mijn kennis schiet te kort om het verschil in de door jou gestelde vraag
goed te kunnen begrijpen. Op zich is de door jou ingestelde tijd van 10
minuten ok.
Ik gebruik de node om bepaalde gegevens (o.a.) bewolkingsgraad in te voren
in Domoticz. Ik heb ook een Domoticz systeem draaien in mijn caravan, dus
daar is een internetverbinding vaak niet beschikbaar. Door gebruik te maken
van een injectnode icm een gate kan jouw node, mits voorzien van een
ingang, geactiveerd worden als ik dat wil.

Overigens excuus voor de late reactie. Dit mailadres bekijk ik eigenlijk te
weinig. In ieder geval hartelijk dank voor jouw tijd en aandacht. Hopelijk
heb ik je voldoende duidelijk kunnen maken waarvoor ik een ingang zal gaan
gebruiken.

Met vriendelijke groet,

Jan.

Op wo 24 jun. 2020 om 12:06 schreef Gilles van den Hoven <
notifications@github.com>:

**Comment by gvdhoven** [comment]
Will be in the next release on the NPM website.

**Comment by janjansen1** [comment]
Hartelijk dank!!

Op za 8 aug. 2020 om 21:50 schreef Gilles van den Hoven <
notifications@github.com>:
