### ISSUE TITLE
Invalid properties: -conf + feature request

### ISSUE THREAD

**Issue by spudje** [Webunity/node-red-contrib-dutch-weather#3]
Cool Node-RED package!! While it actually works, it gives me some an error message. 
"Invalid properties: -conf" See screenshot.
I have configured my GPS coordinates. However there is no other option I can configure, even while the documentation states you can configure the update frequency, It would be cool if we could set that as parameter of the seperate nodes.

![image](https://user-images.githubusercontent.com/53037698/88290809-98c11300-ccf7-11ea-8722-8560053f368b.png)

Additional feature request I have is. Would it be possible to have the rain node also return the full buienalarm rain prediction of every 5 minutes for the coming 2 hours?

**Comment by gvdhoven** [comment]
A new property of the Rain state is added "Sources" with both "Buienalarm" and "Buienradar" as array from now and 120 minutes further.

**Comment by gvdhoven** [comment]
Will be in the next update on NPM
