### ISSUE TITLE
Rain node not updating

### ISSUE THREAD

**Issue by syrisara** [Webunity/node-red-contrib-dutch-weather#4]
Hello,

At first thank you for your nice weather nodes however I'm having some trouble with updating the rain node.

My rain node is updated by an inject node every 5 minutes. As descibed I use {msg.payload = {"trigger":true}} to trigger it.
After some time however the node is not giving any output anymore. The time in between working and not varies.( several minutes to hours)
After restarting my flows or restarting nodered everything works again for minutes to hours.
Other inject nodes work just fine,

Hopefully you can help us/me out,

**Comment by gvdhoven** [comment]
This should have been fixed with latest version, if not i need more info unfortunately.

**Comment by gvdhoven** [comment]
@syrisara i've published v2.0.5; can you check this one out?

**Comment by syrisara** [comment]
Thank you for updating this. Will install the latest version. After that, waiting for rain:-)
