### ISSUE TITLE
Icons: No description / unclear

### ISSUE THREAD

**Issue by Dormin18** [Webunity/node-red-contrib-dutch-weather#5]
Hello,

can someone tell me where to get there graphical icons related to the "icon"-value of the data?
There is something like A007N or C003D, but I have no idea where to get the pics associated to these values.

by the way: the package itself is very good, very useful. Thanks a lot.

Heiner

**Comment by gvdhoven** [comment]
Hi @Dormin18 i tried to look them up but i also could not find them easily :-(
