### ISSUE TITLE
Configuration node not available

### ISSUE THREAD

**Issue by Dunnenj** [Webunity/node-red-contrib-dutch-weather#6]
NR 1.2.9

Installed 2.0.9 using palette. Configuration node is not available.

![image](https://user-images.githubusercontent.com/67200790/114976819-ea618d00-9e86-11eb-8804-7644d976b78a.png)

**Comment by gvdhoven** [comment]
You need to drag one of these onto your flow and edit it, then you can set/update a configuration.

**Comment by Dunnenj** [comment]
I can only set latitude and longitude and in that case nothing will happen. No possibility to set frequency.

Do I need an inject Node? If that is the case what do I need to put in this inject Node, as as single timestamp will not work.

---
John

**Comment by Cafun** [comment]
You need a specific payload indeed. I created a function node for that:

msg.payload = { trigger: true }
return msg;

**Comment by Dunnenj** [comment]
> You need a specific payload indeed. I created a function node for that:
> 
> msg.payload = { trigger: true }
> return msg;

Thanks, this solved my issue.

---
John
