### ISSUE TITLE
No "prediction" in payload

### ISSUE THREAD

**Issue by Cafun** [Webunity/node-red-contrib-dutch-weather#7]
Hello,

It seems there is no "prediction" in the payload anymore.
I'd like to know in how many minutes it will be going to rain.
Can you help me with that?

![image](https://user-images.githubusercontent.com/25382117/117392667-dbed1b00-aef2-11eb-99a8-7f227eb5fbaf.png)

It also looks like the data isn't acurate. It is raining at the moment.
![image](https://user-images.githubusercontent.com/25382117/117392844-2a9ab500-aef3-11eb-9897-a417dadb87a1.png)

Thank you!
Cafun

**Comment by Dunnenj** [comment]
Hello,

I can confirm that the prediction is missing.

Can the issue be fixed / prediction be added?

---
John

**Comment by gvdhoven** [comment]
The prediction is only there if the state changes. I don't know why i've implemented it like that so i have to check. What do you see in the logs when there is an inconsistency? And what is the source from that graph? If it is buienalarm or buienradar it should give the same results in the node.

**Comment by Cafun** [comment]
You mean the Node-RED logs? When I triggered it, there's nog logging in the log.
The source in from that graph is Buienalarm and Buienradar (https://github.com/aex351/home-assistant-neerslag-app).
It doesn't give me the same results.

At 19:05 it is going to rain according to the "Neerslag app". But if I expand the sources and then buienradar, at 19:05 there is no rain predicted.

**Comment by gvdhoven** [comment]
@Cafun i (think) i have fixed the issue but i will also be moving away from this node and move to something that is supported by home-assistant, the neerslag app looks cool, but i don't know how fast it updates.

**Comment by gvdhoven** [comment]
p.s. fixed in 2.0.10

**Comment by Cafun** [comment]
Thank you!
