### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by djalexnl** [Webunity/node-red-contrib-dutch-weather#9]
Hi, i saw this node and installed it to recieve dutch weather info.
Running home assistant hasio core with node red integraded.

installed this node with manage pallet, all fine. 
dragged meteo plaza node to the flow but no output is comming .... ?

`[{"id":"bdd42e12fb122ba6","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"0e871ec6d7cc7907","type":"debug","z":"bdd42e12fb122ba6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":650,"y":160,"wires":[]},{"id":"b35acd64ce58a2f6","type":"dutch-weather-meteoplaza","z":"bdd42e12fb122ba6","conf":"f00a3513efe9a49b","name":"","topic":"","x":430,"y":160,"wires":[["0e871ec6d7cc7907"]]},{"id":"26cc4c38185a41ef","type":"inject","z":"bdd42e12fb122ba6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":160,"wires":[["b35acd64ce58a2f6"]]},{"id":"f00a3513efe9a49b","type":"dutch-weather-conf","lat":"52.2192241","lng":"6.9585846"}]`

what am i doing wrong... 

stil learning node red, started few weeks ago so maybe you can point me in the right direction.

**Comment by Cafun** [comment]
Hi Alex,

You need to send a payload with trigger: true to see the output.
You can read it in de README:
https://github.com/gvdhoven/node-red-contrib-dutch-weather#release-203

**Comment by djalexnl** [comment]
Hi Cafun,

Still nothing....

Please return my node red code working so i can see what you mean.

I changed the payload  to : 

- true (string)
- true boolean
- { trigger: true } (string)

no output.... you shoud make a few examples in your readme file on top... not somewhere documented in old version below.....

Not everyone is a pro, a lot of us try to learn...

**Comment by Cafun** [comment]
I agree with you, it should be on top of the readme file, @gvdhoven it's helpfull for people if you change that.

This is my working code:

`[{"id":"1db23f74.bc8c61","type":"inject","z":"df72a985.e73fd8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1140,"y":120,"wires":[["16af1d53.57e273"]]},{"id":"16af1d53.57e273","type":"function","z":"df72a985.e73fd8","name":"","func":"msg.payload = { trigger: true }\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":1280,"y":120,"wires":[["513271c0.3b1aa","7f0f9019e98d60de"]]},{"id":"7f0f9019e98d60de","type":"dutch-weather-meteoplaza","z":"df72a985.e73fd8","conf":"b3d6f4c5.53b8d8","name":"","topic":"","x":1430,"y":120,"wires":[["446cee5376aa96cb"]]},{"id":"446cee5376aa96cb","type":"debug","z":"df72a985.e73fd8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1570,"y":120,"wires":[]},{"id":"b3d6f4c5.53b8d8","type":"dutch-weather-conf","lat":"51.42408","lng":"5.442794"}]`

**Comment by djalexnl** [comment]
Thanx Cafun!!!!!!!, 

This works great! i never would have come with this solution. 
@gvdhoven Thanx 4 the node works great now. 

Could you add the working code from Cafun to your page? This would help people like me alot! 

Another newbie question, what happends if the node is updated? does it automaticly update in node red?

Thanx Greetz 

Alex

**Comment by Cafun** [comment]
It won't update automatic.
With the inject node you can periodic run it like every 5 minutes.

**Comment by djalexnl** [comment]
Hi Cafun, thanx for the update,

Thats not what i mean. I mean if the package node   that gvdHoven created gets an future update. Does it automaticly update in node read or do you get a message from node red to update etc?

Just installed node red + homeassistant few weeks ago.

Node itself runs fine now I can control my screens perfectly on cloud percantage , max day temp etc.  I indeed use the timer ;-)
 
Greetings... 

Alexander

**Comment by Cafun** [comment]
Ah right :-)
Well, you cold subscribe here on github to get a notification when there is a new release. Then you can go to "Manage Palette" in Node-RED to update the package.

**Comment by gvdhoven** [comment]
Indeed, not an issue anymore :)
